'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class BotMessages
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PeriodiBOT_IRC.BotMessages", GetType(BotMessages).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a  Se añadió {0} extracto nuevo..
    '''</summary>
    Friend Shared ReadOnly Property AddedExtract() As String
        Get
            Return ResourceManager.GetString("AddedExtract", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a  Se añadieron {0} extractos nuevos..
    '''</summary>
    Friend Shared ReadOnly Property AddedExtracts() As String
        Get
            Return ResourceManager.GetString("AddedExtracts", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Aparentemente el resultado es {0}..
    '''</summary>
    Friend Shared ReadOnly Property ApparentResult() As String
        Get
            Return ResourceManager.GetString("ApparentResult", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Bot: Archivando {0} hilo con más de {1} días de antigüedad desde &apos;[[{2}]]&apos;..
    '''</summary>
    Friend Shared ReadOnly Property ArchivedThreadDestSumm() As String
        Get
            Return ResourceManager.GetString("ArchivedThreadDestSumm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Bot: Archivando {0} hilos con más de {1} días de antigüedad desde &apos;[[{2}]]&apos;..
    '''</summary>
    Friend Shared ReadOnly Property ArchivedThreadsDestSumm() As String
        Get
            Return ResourceManager.GetString("ArchivedThreadsDestSumm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Bot: Archivando {0} hilos con más de {1} días de antigüedad..
    '''</summary>
    Friend Shared ReadOnly Property ArchivedThreadsSumm() As String
        Get
            Return ResourceManager.GetString("ArchivedThreadsSumm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Bot: Archivando {0} hilo con más de {1} días de antigüedad..
    '''</summary>
    Friend Shared ReadOnly Property ArchivedThreadSumm() As String
        Get
            Return ResourceManager.GetString("ArchivedThreadSumm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Archivando todas las páginas que incluyan la plantilla &apos;{0}&apos;..
    '''</summary>
    Friend Shared ReadOnly Property ArchivingInclusions() As String
        Get
            Return ResourceManager.GetString("ArchivingInclusions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Autor		: .
    '''</summary>
    Friend Shared ReadOnly Property Author() As String
        Get
            Return ResourceManager.GetString("Author", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Autoarchivando &apos;{0}&apos;..
    '''</summary>
    Friend Shared ReadOnly Property AutoArchive() As String
        Get
            Return ResourceManager.GetString("AutoArchive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Autoarchivado de &apos;{0}&apos; completo..
    '''</summary>
    Friend Shared ReadOnly Property AutoArchiveDone() As String
        Get
            Return ResourceManager.GetString("AutoArchiveDone", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cancelada		: .
    '''</summary>
    Friend Shared ReadOnly Property Cancelled() As String
        Get
            Return ResourceManager.GetString("Cancelled", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La tarea crítica &apos;{0}&apos; no puede ser pausada..
    '''</summary>
    Friend Shared ReadOnly Property CannotPause() As String
        Get
            Return ResourceManager.GetString("CannotPause", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Comprobando el usuario {0}.
    '''</summary>
    Friend Shared ReadOnly Property CheckingUser() As String
        Get
            Return ResourceManager.GetString("CheckingUser", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Verificando si el usuario {0} en el host {1} es OP..
    '''</summary>
    Friend Shared ReadOnly Property CheckOp() As String
        Get
            Return ResourceManager.GetString("CheckOp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Comando &apos;{0}&apos; ingresado por &apos;{1}&apos;. Argumentos: &apos;{2}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property CommandIssued() As String
        Get
            Return ResourceManager.GetString("CommandIssued", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error de conexión. EX: {0}.
    '''</summary>
    Friend Shared ReadOnly Property ConnectionError() As String
        Get
            Return ResourceManager.GetString("ConnectionError", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a (Bot) Creando nueva caja de archivos..
    '''</summary>
    Friend Shared ReadOnly Property CreatingBoxSumm() As String
        Get
            Return ResourceManager.GetString("CreatingBoxSumm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Creando conexión..
    '''</summary>
    Friend Shared ReadOnly Property CreatingConnection() As String
        Get
            Return ResourceManager.GetString("CreatingConnection", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Crítica		: .
    '''</summary>
    Friend Shared ReadOnly Property Critical() As String
        Get
            Return ResourceManager.GetString("Critical", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Log debug desactivado..
    '''</summary>
    Friend Shared ReadOnly Property DebugDisabled() As String
        Get
            Return ResourceManager.GetString("DebugDisabled", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Log debug activado..
    '''</summary>
    Friend Shared ReadOnly Property DebugEnabled() As String
        Get
            Return ResourceManager.GetString("DebugEnabled", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Dividiendo por 0....
    '''</summary>
    Friend Shared ReadOnly Property Div0() As String
        Get
            Return ResourceManager.GetString("Div0", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Entrando a {0}..
    '''</summary>
    Friend Shared ReadOnly Property EnteringRoom() As String
        Get
            Return ResourceManager.GetString("EnteringRoom", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ingrese el número de la tarea..
    '''</summary>
    Friend Shared ReadOnly Property EnterTaskNumber() As String
        Get
            Return ResourceManager.GetString("EnterTaskNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Errores		: .
    '''</summary>
    Friend Shared ReadOnly Property Errors() As String
        Get
            Return ResourceManager.GetString("Errors", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cada {0} segundos..
    '''</summary>
    Friend Shared ReadOnly Property EverySec() As String
        Get
            Return ResourceManager.GetString("EverySec", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Eejcuciones	: .
    '''</summary>
    Friend Shared ReadOnly Property Executions() As String
        Get
            Return ResourceManager.GetString("Executions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a OK, me voy....
    '''</summary>
    Friend Shared ReadOnly Property ExitMessage() As String
        Get
            Return ResourceManager.GetString("ExitMessage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al crear el archivo &apos;{0}&apos;..
    '''</summary>
    Friend Shared ReadOnly Property FileCreateErr() As String
        Get
            Return ResourceManager.GetString("FileCreateErr", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al guardar el archivo &apos;{0}&apos;..
    '''</summary>
    Friend Shared ReadOnly Property FileSaveErr() As String
        Get
            Return ResourceManager.GetString("FileSaveErr", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cargando el extracto de la página &apos;{0}&apos;..
    '''</summary>
    Friend Shared ReadOnly Property GetPageExtract() As String
        Get
            Return ResourceManager.GetString("GetPageExtract", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cargando {0} extractos de páginas..
    '''</summary>
    Friend Shared ReadOnly Property GetPagesExtract() As String
        Get
            Return ResourceManager.GetString("GetPagesExtract", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Infinita		: .
    '''</summary>
    Friend Shared ReadOnly Property Infinite() As String
        Get
            Return ResourceManager.GetString("Infinite", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El espacio de nombres de la página &apos;{0}&apos; ({1}) es inválido..
    '''</summary>
    Friend Shared ReadOnly Property InvalidNamespace() As String
        Get
            Return ResourceManager.GetString("InvalidNamespace", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Parámetro inválido..
    '''</summary>
    Friend Shared ReadOnly Property InvalidParameter() As String
        Get
            Return ResourceManager.GetString("InvalidParameter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Invalid parameter..
    '''</summary>
    Friend Shared ReadOnly Property InvalidParameter1() As String
        Get
            Return ResourceManager.GetString("InvalidParameter1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El usuario &apos;{0}&apos; no cumple con los requisitos mínimos de archivado..
    '''</summary>
    Friend Shared ReadOnly Property InvalidUserArchive() As String
        Get
            Return ResourceManager.GetString("InvalidUserArchive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Entrando al canal {0}..
    '''</summary>
    Friend Shared ReadOnly Property JoiningChannel() As String
        Get
            Return ResourceManager.GetString("JoiningChannel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Saliendo de {0}..
    '''</summary>
    Friend Shared ReadOnly Property LeavingRoom() As String
        Get
            Return ResourceManager.GetString("LeavingRoom", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cargando {0} resúmenes nuevos..
    '''</summary>
    Friend Shared ReadOnly Property LoadingNewExtracts() As String
        Get
            Return ResourceManager.GetString("LoadingNewExtracts", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cargando {0} resúmenes antiguos..
    '''</summary>
    Friend Shared ReadOnly Property LoadingOldExtracts() As String
        Get
            Return ResourceManager.GetString("LoadingOldExtracts", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cargando operadores..
    '''</summary>
    Friend Shared ReadOnly Property LoadingOPs() As String
        Get
            Return ResourceManager.GetString("LoadingOPs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Conexión perdida. Reintentando en {0} segundos..
    '''</summary>
    Friend Shared ReadOnly Property LostConnectionRET() As String
        Get
            Return ResourceManager.GetString("LostConnectionRET", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La plantilla de archivado en la página &apos;{0}&apos; está malformada..
    '''</summary>
    Friend Shared ReadOnly Property MalformedArchiveConfig() As String
        Get
            Return ResourceManager.GetString("MalformedArchiveConfig", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Archivo de operadores malformado..
    '''</summary>
    Friend Shared ReadOnly Property MalformedOPs() As String
        Get
            Return ResourceManager.GetString("MalformedOPs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El valor debe ser superior a {0}..
    '''</summary>
    Friend Shared ReadOnly Property MustBeGreaterThan() As String
        Get
            Return ResourceManager.GetString("MustBeGreaterThan", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Nombre		: .
    '''</summary>
    Friend Shared ReadOnly Property Name() As String
        Get
            Return ResourceManager.GetString("Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Dirección del servidor de IRC principal: .
    '''</summary>
    Friend Shared ReadOnly Property NewIrcNetworkAdress() As String
        Get
            Return ResourceManager.GetString("NewIrcNetworkAdress", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Canales de IRC (separados por pipe [|]): .
    '''</summary>
    Friend Shared ReadOnly Property NewIrcNetworkChannels() As String
        Get
            Return ResourceManager.GetString("NewIrcNetworkChannels", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Nickname en el servidor IRC: .
    '''</summary>
    Friend Shared ReadOnly Property NewIrcNetworkNickName() As String
        Get
            Return ResourceManager.GetString("NewIrcNetworkNickName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Contraseña de Nickserv o de servidor: .
    '''</summary>
    Friend Shared ReadOnly Property NewIrcNetworkPass() As String
        Get
            Return ResourceManager.GetString("NewIrcNetworkPass", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Operador IRC (Nickname!hostname):.
    '''</summary>
    Friend Shared ReadOnly Property NewOp() As String
        Get
            Return ResourceManager.GetString("NewOp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a . El próximo aviso será en 5 minutos..
    '''</summary>
    Friend Shared ReadOnly Property NextNotif() As String
        Get
            Return ResourceManager.GetString("NextNotif", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Intentando autenticar via nickserv..
    '''</summary>
    Friend Shared ReadOnly Property NickervAuth() As String
        Get
            Return ResourceManager.GetString("NickervAuth", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No existe el archivo de configuracion IRC.
    '''</summary>
    Friend Shared ReadOnly Property NoIrcConfigFile() As String
        Get
            Return ResourceManager.GetString("NoIrcConfigFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No se ha definido ningun operador..
    '''</summary>
    Friend Shared ReadOnly Property NoOp() As String
        Get
            Return ResourceManager.GetString("NoOp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El archivo de operadores no existe..
    '''</summary>
    Friend Shared ReadOnly Property NoOpsFile() As String
        Get
            Return ResourceManager.GetString("NoOpsFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No hay tareas en ejecución..
    '''</summary>
    Friend Shared ReadOnly Property NoRunningTasks() As String
        Get
            Return ResourceManager.GetString("NoRunningTasks", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La página &apos;{0}&apos; no es una subpágina de la página principal (&apos;{1}&apos;)..
    '''</summary>
    Friend Shared ReadOnly Property NotASubPage() As String
        Get
            Return ResourceManager.GetString("NotASubPage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No conectado..
    '''</summary>
    Friend Shared ReadOnly Property NotConnected() As String
        Get
            Return ResourceManager.GetString("NotConnected", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No hay hilos por archivar en &apos;{0}&apos;..
    '''</summary>
    Friend Shared ReadOnly Property NothingToArchive() As String
        Get
            Return ResourceManager.GetString("NothingToArchive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El parámetro es nulo..
    '''</summary>
    Friend Shared ReadOnly Property NullParameter() As String
        Get
            Return ResourceManager.GetString("NullParameter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ingrese un valor numérico.
    '''</summary>
    Friend Shared ReadOnly Property NumericValue() As String
        Get
            Return ResourceManager.GetString("NumericValue", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a  Se omitió {0} extracto inseguro..
    '''</summary>
    Friend Shared ReadOnly Property OmittedExtract() As String
        Get
            Return ResourceManager.GetString("OmittedExtract", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a  Se omitieron {0} extractos inseguros..
    '''</summary>
    Friend Shared ReadOnly Property OmittedExtracts() As String
        Get
            Return ResourceManager.GetString("OmittedExtracts", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La página &apos;{0}&apos; solo tiene un hilo..
    '''</summary>
    Friend Shared ReadOnly Property OneThreadPage() As String
        Get
            Return ResourceManager.GetString("OneThreadPage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El usuario {0} ha sido añadido como operador..
    '''</summary>
    Friend Shared ReadOnly Property OpAdded() As String
        Get
            Return ResourceManager.GetString("OpAdded", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El usuario {0} no ha sido añadido como operador..
    '''</summary>
    Friend Shared ReadOnly Property OpNotAdded() As String
        Get
            Return ResourceManager.GetString("OpNotAdded", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a {0} no es un operador..
    '''</summary>
    Friend Shared ReadOnly Property OpNotRemoved() As String
        Get
            Return ResourceManager.GetString("OpNotRemoved", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a {0} ya no es un operador..
    '''</summary>
    Friend Shared ReadOnly Property OpRemoved() As String
        Get
            Return ResourceManager.GetString("OpRemoved", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a (Bot) Creando una nueva caja de archivos por sobre una ya existente..
    '''</summary>
    Friend Shared ReadOnly Property OverwritingBoxSumm() As String
        Get
            Return ResourceManager.GetString("OverwritingBoxSumm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Pausada		: .
    '''</summary>
    Friend Shared ReadOnly Property Paused() As String
        Get
            Return ResourceManager.GetString("Paused", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Tarea &apos;{0}&apos; pausada..
    '''</summary>
    Friend Shared ReadOnly Property PausedTask() As String
        Get
            Return ResourceManager.GetString("PausedTask", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Periódica.
    '''</summary>
    Friend Shared ReadOnly Property Periodic() As String
        Get
            Return ResourceManager.GetString("Periodic", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Recreando texto..
    '''</summary>
    Friend Shared ReadOnly Property RecreatingText() As String
        Get
            Return ResourceManager.GetString("RecreatingText", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Solicitado por un operador..
    '''</summary>
    Friend Shared ReadOnly Property RequestedByOp() As String
        Get
            Return ResourceManager.GetString("RequestedByOp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Hay {0} tareas ejecutándose en este momento..
    '''</summary>
    Friend Shared ReadOnly Property RunningTasks() As String
        Get
            Return ResourceManager.GetString("RunningTasks", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Estableciendo nombre..
    '''</summary>
    Friend Shared ReadOnly Property SetName() As String
        Get
            Return ResourceManager.GetString("SetName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Estableciendo nickname..
    '''</summary>
    Friend Shared ReadOnly Property SetNick() As String
        Get
            Return ResourceManager.GetString("SetNick", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Programada.
    '''</summary>
    Friend Shared ReadOnly Property Sheduled() As String
        Get
            Return ResourceManager.GetString("Sheduled", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Starting IRC client..
    '''</summary>
    Friend Shared ReadOnly Property StartingIRCClient() As String
        Get
            Return ResourceManager.GetString("StartingIRCClient", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Estado		: .
    '''</summary>
    Friend Shared ReadOnly Property Status() As String
        Get
            Return ResourceManager.GetString("Status", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Operación exitosa..
    '''</summary>
    Friend Shared ReadOnly Property SuccessfulOperation() As String
        Get
            Return ResourceManager.GetString("SuccessfulOperation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La hora del sistema es: .
    '''</summary>
    Friend Shared ReadOnly Property SystemTime() As String
        Get
            Return ResourceManager.GetString("SystemTime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a {0}: {1} por {2}. Estado: {3}..
    '''</summary>
    Friend Shared ReadOnly Property TaskInfo() As String
        Get
            Return ResourceManager.GetString("TaskInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La tarea no existe..
    '''</summary>
    Friend Shared ReadOnly Property TaskNotExist() As String
        Get
            Return ResourceManager.GetString("TaskNotExist", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Tiempo/Intervalo	: .
    '''</summary>
    Friend Shared ReadOnly Property TimeOrInterval() As String
        Get
            Return ResourceManager.GetString("TimeOrInterval", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Intentando guardar &apos;{0}&apos;..
    '''</summary>
    Friend Shared ReadOnly Property TryingToSave() As String
        Get
            Return ResourceManager.GetString("TryingToSave", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Tipo		: .
    '''</summary>
    Friend Shared ReadOnly Property Type() As String
        Get
            Return ResourceManager.GetString("Type", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No autorizado..
    '''</summary>
    Friend Shared ReadOnly Property Unauthorized() As String
        Get
            Return ResourceManager.GetString("Unauthorized", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Excepción inesperada: {0}.
    '''</summary>
    Friend Shared ReadOnly Property UnexpectedEX() As String
        Get
            Return ResourceManager.GetString("UnexpectedEX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Tarea &apos;{0}&apos; despausada..
    '''</summary>
    Friend Shared ReadOnly Property UnpausedTask() As String
        Get
            Return ResourceManager.GetString("UnpausedTask", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Bot: Añadiendo firma faltante de &apos;{0}&apos;..
    '''</summary>
    Friend Shared ReadOnly Property UnsignedSumm() As String
        Get
            Return ResourceManager.GetString("UnsignedSumm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La operación ha fallado..
    '''</summary>
    Friend Shared ReadOnly Property UnsuccessfulOperation() As String
        Get
            Return ResourceManager.GetString("UnsuccessfulOperation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al actualizar la caja de archivos en &apos;{0}&apos;. EX: {1}.
    '''</summary>
    Friend Shared ReadOnly Property UpdateBoxEx() As String
        Get
            Return ResourceManager.GetString("UpdateBoxEx", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Bot: {0} resúmenes actualizados..
    '''</summary>
    Friend Shared ReadOnly Property UpdatedExtracts() As String
        Get
            Return ResourceManager.GetString("UpdatedExtracts", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Actualizando caja de archivos..
    '''</summary>
    Friend Shared ReadOnly Property UpdatingArchiveBox() As String
        Get
            Return ResourceManager.GetString("UpdatingArchiveBox", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Bot: Actualizando caja de archivos..
    '''</summary>
    Friend Shared ReadOnly Property UpdatingBoxSumm() As String
        Get
            Return ResourceManager.GetString("UpdatingBoxSumm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Bot: Actualizando contador..
    '''</summary>
    Friend Shared ReadOnly Property UpdatingCount() As String
        Get
            Return ResourceManager.GetString("UpdatingCount", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El usuario {0} está bloqueado..
    '''</summary>
    Friend Shared ReadOnly Property UserBlocked() As String
        Get
            Return ResourceManager.GetString("UserBlocked", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La última edición de {0} fue hace {1} día..
    '''</summary>
    Friend Shared ReadOnly Property UserEditedDay() As String
        Get
            Return ResourceManager.GetString("UserEditedDay", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La última edición de {0} fue hace {1} días..
    '''</summary>
    Friend Shared ReadOnly Property UserEditedDays() As String
        Get
            Return ResourceManager.GetString("UserEditedDays", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La última edición de {0} fue hace {1} hora..
    '''</summary>
    Friend Shared ReadOnly Property UserEditedHour() As String
        Get
            Return ResourceManager.GetString("UserEditedHour", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La última edición de {0} fue hace {1} horas..
    '''</summary>
    Friend Shared ReadOnly Property UserEditedHours() As String
        Get
            Return ResourceManager.GetString("UserEditedHours", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La última edición de {0} fue hace {1} minutos..
    '''</summary>
    Friend Shared ReadOnly Property UserEditedMinutes() As String
        Get
            Return ResourceManager.GetString("UserEditedMinutes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El usuario {0} está inactivo..
    '''</summary>
    Friend Shared ReadOnly Property UserInactive() As String
        Get
            Return ResourceManager.GetString("UserInactive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El usuario {0} no existe..
    '''</summary>
    Friend Shared ReadOnly Property UserInexistent() As String
        Get
            Return ResourceManager.GetString("UserInexistent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El usuario {0} no tiene ediciones en esta Wiki..
    '''</summary>
    Friend Shared ReadOnly Property UserNoEdits() As String
        Get
            Return ResourceManager.GetString("UserNoEdits", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El usuario {0} en el host {1} no es OP..
    '''</summary>
    Friend Shared ReadOnly Property UserNotOp() As String
        Get
            Return ResourceManager.GetString("UserNotOp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El usuario {0} en el host {1} es OP..
    '''</summary>
    Friend Shared ReadOnly Property UserOP() As String
        Get
            Return ResourceManager.GetString("UserOP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El valor es demasiado grande..
    '''</summary>
    Friend Shared ReadOnly Property ValueTooBig() As String
        Get
            Return ResourceManager.GetString("ValueTooBig", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Tiempo de espera: {0}ms..
    '''</summary>
    Friend Shared ReadOnly Property WaitingTime() As String
        Get
            Return ResourceManager.GetString("WaitingTime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error en un hilo de la página &apos;{0}&apos;. Hilo número {1}. EX: {2}.
    '''</summary>
    Friend Shared ReadOnly Property WikiThreadError() As String
        Get
            Return ResourceManager.GetString("WikiThreadError", resourceCulture)
        End Get
    End Property
End Class
