'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PeriodiBOT_IRC.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PeriodiBOT .
        '''</summary>
        Friend Shared ReadOnly Property BotEngine() As String
            Get
                Return ResourceManager.GetString("BotEngine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Malformed config file.
        '''</summary>
        Friend Shared ReadOnly Property ConfigError() As String
            Get
                Return ResourceManager.GetString("ConfigError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Done, {0} pages returned..
        '''</summary>
        Friend Shared ReadOnly Property DoneXPagesReturned() As String
            Get
                Return ResourceManager.GetString("DoneXPagesReturned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Getting the last revid of {0} pages..
        '''</summary>
        Friend Shared ReadOnly Property GetLastrevIDs() As String
            Get
                Return ResourceManager.GetString("GetLastrevIDs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ==================== PeriodiBOT {0} ====================.
        '''</summary>
        Friend Shared ReadOnly Property GreetingMsg() As String
            Get
                Return ResourceManager.GetString("GreetingMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The url is invalid..
        '''</summary>
        Friend Shared ReadOnly Property InvalidUrl() As String
            Get
                Return ResourceManager.GetString("InvalidUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Loading config.
        '''</summary>
        Friend Shared ReadOnly Property LoadingConfig() As String
            Get
                Return ResourceManager.GetString("LoadingConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login failed.
        '''</summary>
        Friend Shared ReadOnly Property LoginError() As String
            Get
                Return ResourceManager.GetString("LoginError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login ID: .
        '''</summary>
        Friend Shared ReadOnly Property LoginID() As String
            Get
                Return ResourceManager.GetString("LoginID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login result: .
        '''</summary>
        Friend Shared ReadOnly Property LoginResult() As String
            Get
                Return ResourceManager.GetString("LoginResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Network error: .
        '''</summary>
        Friend Shared ReadOnly Property NetworkError() As String
            Get
                Return ResourceManager.GetString("NetworkError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Bot name: .
        '''</summary>
        Friend Shared ReadOnly Property NewBotName() As String
            Get
                Return ResourceManager.GetString("NewBotName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wiki BOT password: .
        '''</summary>
        Friend Shared ReadOnly Property NewBotPassword() As String
            Get
                Return ResourceManager.GetString("NewBotPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error creating a new config file.
        '''</summary>
        Friend Shared ReadOnly Property NewConfigFileError() As String
            Get
                Return ResourceManager.GetString("NewConfigFileError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a There is no config file, please fill the following data or close the program and manually create a new config file..
        '''</summary>
        Friend Shared ReadOnly Property NewConfigMessage() As String
            Get
                Return ResourceManager.GetString("NewConfigMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IRC server main adress: .
        '''</summary>
        Friend Shared ReadOnly Property NewIrcNetworkAdress() As String
            Get
                Return ResourceManager.GetString("NewIrcNetworkAdress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IRC channels (separated by pipes [|]): .
        '''</summary>
        Friend Shared ReadOnly Property NewIrcNetworkChannels() As String
            Get
                Return ResourceManager.GetString("NewIrcNetworkChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IRC Nickname: .
        '''</summary>
        Friend Shared ReadOnly Property NewIrcNetworkNickName() As String
            Get
                Return ResourceManager.GetString("NewIrcNetworkNickName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IRC Nickserv/Server password: .
        '''</summary>
        Friend Shared ReadOnly Property NewIrcNetworkPass() As String
            Get
                Return ResourceManager.GetString("NewIrcNetworkPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wiki username: .
        '''</summary>
        Friend Shared ReadOnly Property NewUsername() As String
            Get
                Return ResourceManager.GetString("NewUsername", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wiki API Url: .
        '''</summary>
        Friend Shared ReadOnly Property NewWikiMainApiUrl() As String
            Get
                Return ResourceManager.GetString("NewWikiMainApiUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wiki Url: .
        '''</summary>
        Friend Shared ReadOnly Property NewWikiMainUrl() As String
            Get
                Return ResourceManager.GetString("NewWikiMainUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No config file.
        '''</summary>
        Friend Shared ReadOnly Property NoConfigFile() As String
            Get
                Return ResourceManager.GetString("NoConfigFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Press any key to exit.
        '''</summary>
        Friend Shared ReadOnly Property PressKey() As String
            Get
                Return ResourceManager.GetString("PressKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reason: .
        '''</summary>
        Friend Shared ReadOnly Property Reason() As String
            Get
                Return ResourceManager.GetString("Reason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Requesting token.
        '''</summary>
        Friend Shared ReadOnly Property RequestingToken() As String
            Get
                Return ResourceManager.GetString("RequestingToken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error saving the config..
        '''</summary>
        Friend Shared ReadOnly Property SaveConfigError() As String
            Get
                Return ResourceManager.GetString("SaveConfigError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Signing in.
        '''</summary>
        Friend Shared ReadOnly Property SigninIn() As String
            Get
                Return ResourceManager.GetString("SigninIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Token obtained.
        '''</summary>
        Friend Shared ReadOnly Property TokenObtained() As String
            Get
                Return ResourceManager.GetString("TokenObtained", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User name: .
        '''</summary>
        Friend Shared ReadOnly Property Username() As String
            Get
                Return ResourceManager.GetString("Username", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
