'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PeriodiBOT_IRC.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  {0} new extract has been added..
        '''</summary>
        Friend Shared ReadOnly Property AddedExtract() As String
            Get
                Return ResourceManager.GetString("AddedExtract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  {0} new extracts have been added..
        '''</summary>
        Friend Shared ReadOnly Property AddedExtracts() As String
            Get
                Return ResourceManager.GetString("AddedExtracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (Bot) Archiving {0} thread with more than {1} days old from [[&apos;{2}&apos;]]..
        '''</summary>
        Friend Shared ReadOnly Property ArchivedThreadDestSumm() As String
            Get
                Return ResourceManager.GetString("ArchivedThreadDestSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (Bot) Archiving {0} threads with more than {1} days old from [[&apos;{2}&apos;]]..
        '''</summary>
        Friend Shared ReadOnly Property ArchivedThreadsDestSumm() As String
            Get
                Return ResourceManager.GetString("ArchivedThreadsDestSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (Bot) Archiving {0} threads with more than {1} days old..
        '''</summary>
        Friend Shared ReadOnly Property ArchivedThreadsSumm() As String
            Get
                Return ResourceManager.GetString("ArchivedThreadsSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (Bot) Archiving {0} thread with more than {1} days old..
        '''</summary>
        Friend Shared ReadOnly Property ArchivedThreadSumm() As String
            Get
                Return ResourceManager.GetString("ArchivedThreadSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Archiving all pages that includes the template &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property ArchivingInclusions() As String
            Get
                Return ResourceManager.GetString("ArchivingInclusions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Autoarchiving &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property AutoArchive() As String
            Get
                Return ResourceManager.GetString("AutoArchive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Auto-archive of &apos;{0}&apos; done..
        '''</summary>
        Friend Shared ReadOnly Property AutoArchiveDone() As String
            Get
                Return ResourceManager.GetString("AutoArchiveDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PeriodiBOT .
        '''</summary>
        Friend Shared ReadOnly Property BotEngine() As String
            Get
                Return ResourceManager.GetString("BotEngine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Checking user {0}.
        '''</summary>
        Friend Shared ReadOnly Property CheckingUser() As String
            Get
                Return ResourceManager.GetString("CheckingUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Checking users..
        '''</summary>
        Friend Shared ReadOnly Property CheckingUsers() As String
            Get
                Return ResourceManager.GetString("CheckingUsers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Malformed config file..
        '''</summary>
        Friend Shared ReadOnly Property ConfigError() As String
            Get
                Return ResourceManager.GetString("ConfigError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (Bot) Creating archive box..
        '''</summary>
        Friend Shared ReadOnly Property CreatingBoxSumm() As String
            Get
                Return ResourceManager.GetString("CreatingBoxSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Creating Connection..
        '''</summary>
        Friend Shared ReadOnly Property CreatingConnection() As String
            Get
                Return ResourceManager.GetString("CreatingConnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Done, {0} pages returned..
        '''</summary>
        Friend Shared ReadOnly Property DoneXPagesReturned() As String
            Get
                Return ResourceManager.GetString("DoneXPagesReturned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Getting the last revid of {0} pages..
        '''</summary>
        Friend Shared ReadOnly Property GetLastrevIDs() As String
            Get
                Return ResourceManager.GetString("GetLastrevIDs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Loading page extract of &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property GetPageExtract() As String
            Get
                Return ResourceManager.GetString("GetPageExtract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Loading {0} pages extract..
        '''</summary>
        Friend Shared ReadOnly Property GetPagesExtract() As String
            Get
                Return ResourceManager.GetString("GetPagesExtract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ==================== PeriodiBOT {0} ====================.
        '''</summary>
        Friend Shared ReadOnly Property GreetingMsg() As String
            Get
                Return ResourceManager.GetString("GreetingMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The namespace of &apos;{0}&apos; ({1}) is invalid..
        '''</summary>
        Friend Shared ReadOnly Property InvalidNamespace() As String
            Get
                Return ResourceManager.GetString("InvalidNamespace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The url is invalid..
        '''</summary>
        Friend Shared ReadOnly Property InvalidUrl() As String
            Get
                Return ResourceManager.GetString("InvalidUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The user &apos;{0}&apos; is invalid..
        '''</summary>
        Friend Shared ReadOnly Property InvalidUser() As String
            Get
                Return ResourceManager.GetString("InvalidUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The user &apos;{0}&apos; doesn&apos;t meet the minimum archive requirements..
        '''</summary>
        Friend Shared ReadOnly Property InvalidUserArchive() As String
            Get
                Return ResourceManager.GetString("InvalidUserArchive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Joining channel {0}..
        '''</summary>
        Friend Shared ReadOnly Property JoiningChannel() As String
            Get
                Return ResourceManager.GetString("JoiningChannel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Loading config.
        '''</summary>
        Friend Shared ReadOnly Property LoadingConfig() As String
            Get
                Return ResourceManager.GetString("LoadingConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Loading {0} new extracts.
        '''</summary>
        Friend Shared ReadOnly Property LoadingNewExtracts() As String
            Get
                Return ResourceManager.GetString("LoadingNewExtracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Loading {0} old extracts.
        '''</summary>
        Friend Shared ReadOnly Property LoadingOldExtracts() As String
            Get
                Return ResourceManager.GetString("LoadingOldExtracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login failed.
        '''</summary>
        Friend Shared ReadOnly Property LoginError() As String
            Get
                Return ResourceManager.GetString("LoginError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login ID: .
        '''</summary>
        Friend Shared ReadOnly Property LoginID() As String
            Get
                Return ResourceManager.GetString("LoginID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login result: .
        '''</summary>
        Friend Shared ReadOnly Property LoginResult() As String
            Get
                Return ResourceManager.GetString("LoginResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The archive template on the page &apos;{0}&apos; is malformed..
        '''</summary>
        Friend Shared ReadOnly Property MalformedArchiveConfig() As String
            Get
                Return ResourceManager.GetString("MalformedArchiveConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Network error: .
        '''</summary>
        Friend Shared ReadOnly Property NetworkError() As String
            Get
                Return ResourceManager.GetString("NetworkError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Bot name: .
        '''</summary>
        Friend Shared ReadOnly Property NewBotName() As String
            Get
                Return ResourceManager.GetString("NewBotName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wiki BOT password: .
        '''</summary>
        Friend Shared ReadOnly Property NewBotPassword() As String
            Get
                Return ResourceManager.GetString("NewBotPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error creating a new config file.
        '''</summary>
        Friend Shared ReadOnly Property NewConfigFileError() As String
            Get
                Return ResourceManager.GetString("NewConfigFileError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a There is no config file, please fill the following data or close the program and manually create a new config file..
        '''</summary>
        Friend Shared ReadOnly Property NewConfigMessage() As String
            Get
                Return ResourceManager.GetString("NewConfigMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IRC server main adress: .
        '''</summary>
        Friend Shared ReadOnly Property NewIrcNetworkAdress() As String
            Get
                Return ResourceManager.GetString("NewIrcNetworkAdress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IRC channels (separated by pipes [|]): .
        '''</summary>
        Friend Shared ReadOnly Property NewIrcNetworkChannels() As String
            Get
                Return ResourceManager.GetString("NewIrcNetworkChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IRC Nickname: .
        '''</summary>
        Friend Shared ReadOnly Property NewIrcNetworkNickName() As String
            Get
                Return ResourceManager.GetString("NewIrcNetworkNickName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IRC Nickserv/Server password: .
        '''</summary>
        Friend Shared ReadOnly Property NewIrcNetworkPass() As String
            Get
                Return ResourceManager.GetString("NewIrcNetworkPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wiki username: .
        '''</summary>
        Friend Shared ReadOnly Property NewUserName() As String
            Get
                Return ResourceManager.GetString("NewUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wiki API Url: .
        '''</summary>
        Friend Shared ReadOnly Property NewWikiMainApiUrl() As String
            Get
                Return ResourceManager.GetString("NewWikiMainApiUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wiki Url: .
        '''</summary>
        Friend Shared ReadOnly Property NewWikiMainUrl() As String
            Get
                Return ResourceManager.GetString("NewWikiMainUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a . The next notice will be in 5 minutes..
        '''</summary>
        Friend Shared ReadOnly Property NextNotif() As String
            Get
                Return ResourceManager.GetString("NextNotif", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Attempting nickserv auth..
        '''</summary>
        Friend Shared ReadOnly Property NickervAuth() As String
            Get
                Return ResourceManager.GetString("NickervAuth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No config file.
        '''</summary>
        Friend Shared ReadOnly Property NoConfigFile() As String
            Get
                Return ResourceManager.GetString("NoConfigFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The page &apos;{0}&apos; is not a subpage of the main page (&apos;{1}&apos;)..
        '''</summary>
        Friend Shared ReadOnly Property NotASubPage() As String
            Get
                Return ResourceManager.GetString("NotASubPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nothing to archive on &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property NothingToArchive() As String
            Get
                Return ResourceManager.GetString("NothingToArchive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The parameter is null..
        '''</summary>
        Friend Shared ReadOnly Property NullParameter() As String
            Get
                Return ResourceManager.GetString("NullParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  {0} unsafe extract has been omitted..
        '''</summary>
        Friend Shared ReadOnly Property OmittedExtract() As String
            Get
                Return ResourceManager.GetString("OmittedExtract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  {0} unsafe extracts have been omitted..
        '''</summary>
        Friend Shared ReadOnly Property OmittedExtracts() As String
            Get
                Return ResourceManager.GetString("OmittedExtracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The page &apos;{0}&apos; only have one thread..
        '''</summary>
        Friend Shared ReadOnly Property OneThreadPage() As String
            Get
                Return ResourceManager.GetString("OneThreadPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Server error on ORES query score from revid {0} (invalid diff?).
        '''</summary>
        Friend Shared ReadOnly Property OresQueryError() As String
            Get
                Return ResourceManager.GetString("OresQueryError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ORES query from revid {0} EX: {1}.
        '''</summary>
        Friend Shared ReadOnly Property OresQueryEx() As String
            Get
                Return ResourceManager.GetString("OresQueryEx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ORES query for revid {0} done. GF: {1} DMG: {2}.
        '''</summary>
        Friend Shared ReadOnly Property OresQueryResult() As String
            Get
                Return ResourceManager.GetString("OresQueryResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (Bot) Creating a new archive box over an existing one..
        '''</summary>
        Friend Shared ReadOnly Property OverwritingBoxSumm() As String
            Get
                Return ResourceManager.GetString("OverwritingBoxSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Page &apos;{0}&apos; loaded..
        '''</summary>
        Friend Shared ReadOnly Property PageLoaded() As String
            Get
                Return ResourceManager.GetString("PageLoaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Press any key to exit.
        '''</summary>
        Friend Shared ReadOnly Property PressKey() As String
            Get
                Return ResourceManager.GetString("PressKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reason: .
        '''</summary>
        Friend Shared ReadOnly Property Reason() As String
            Get
                Return ResourceManager.GetString("Reason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recreating text..
        '''</summary>
        Friend Shared ReadOnly Property RecreatingText() As String
            Get
                Return ResourceManager.GetString("RecreatingText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Requesting token.
        '''</summary>
        Friend Shared ReadOnly Property RequestingToken() As String
            Get
                Return ResourceManager.GetString("RequestingToken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error saving the config..
        '''</summary>
        Friend Shared ReadOnly Property SaveConfigError() As String
            Get
                Return ResourceManager.GetString("SaveConfigError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Setting name..
        '''</summary>
        Friend Shared ReadOnly Property SetName() As String
            Get
                Return ResourceManager.GetString("SetName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Setting nickname..
        '''</summary>
        Friend Shared ReadOnly Property SetNick() As String
            Get
                Return ResourceManager.GetString("SetNick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Signing in.
        '''</summary>
        Friend Shared ReadOnly Property SigninIn() As String
            Get
                Return ResourceManager.GetString("SigninIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Starting IRC client..
        '''</summary>
        Friend Shared ReadOnly Property StartingIRCClient() As String
            Get
                Return ResourceManager.GetString("StartingIRCClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Successful operation..
        '''</summary>
        Friend Shared ReadOnly Property SuccessfulOperation() As String
            Get
                Return ResourceManager.GetString("SuccessfulOperation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (Bot) Replacing &apos;{0}&apos; with &apos;{1}&apos; {2}..
        '''</summary>
        Friend Shared ReadOnly Property TextReplaced() As String
            Get
                Return ResourceManager.GetString("TextReplaced", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Token obtained.
        '''</summary>
        Friend Shared ReadOnly Property TokenObtained() As String
            Get
                Return ResourceManager.GetString("TokenObtained", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Trying to save &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property TryingToSave() As String
            Get
                Return ResourceManager.GetString("TryingToSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (Bot) Adding {0}&apos;s missing signature..
        '''</summary>
        Friend Shared ReadOnly Property UnsignedSumm() As String
            Get
                Return ResourceManager.GetString("UnsignedSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Unsuccessful operation..
        '''</summary>
        Friend Shared ReadOnly Property UnsuccessfulOperation() As String
            Get
                Return ResourceManager.GetString("UnsuccessfulOperation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error updating the archive box on &apos;{0}&apos;. EX: {1}.
        '''</summary>
        Friend Shared ReadOnly Property UpdateBoxEx() As String
            Get
                Return ResourceManager.GetString("UpdateBoxEx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (Bot) Updated {0} resumes..
        '''</summary>
        Friend Shared ReadOnly Property UpdatedExtracts() As String
            Get
                Return ResourceManager.GetString("UpdatedExtracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (Bot) Updating archive box..
        '''</summary>
        Friend Shared ReadOnly Property UpdatingBoxSumm() As String
            Get
                Return ResourceManager.GetString("UpdatingBoxSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User {0} is blocked..
        '''</summary>
        Friend Shared ReadOnly Property UserBlocked() As String
            Get
                Return ResourceManager.GetString("UserBlocked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The last edit of {0} was {1} day ago..
        '''</summary>
        Friend Shared ReadOnly Property UserEditedDay() As String
            Get
                Return ResourceManager.GetString("UserEditedDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The last edit of {0} was {1} days ago..
        '''</summary>
        Friend Shared ReadOnly Property UserEditedDays() As String
            Get
                Return ResourceManager.GetString("UserEditedDays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The last edit of {0} was {1} hour ago..
        '''</summary>
        Friend Shared ReadOnly Property UserEditedHour() As String
            Get
                Return ResourceManager.GetString("UserEditedHour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The last edit of {0} was {1} hours ago..
        '''</summary>
        Friend Shared ReadOnly Property UserEditedHours() As String
            Get
                Return ResourceManager.GetString("UserEditedHours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The last edit of {0} was {1} minutes ago..
        '''</summary>
        Friend Shared ReadOnly Property UserEditedMinutes() As String
            Get
                Return ResourceManager.GetString("UserEditedMinutes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User {0} is inactive..
        '''</summary>
        Friend Shared ReadOnly Property UserInactive() As String
            Get
                Return ResourceManager.GetString("UserInactive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User {0} does not exist..
        '''</summary>
        Friend Shared ReadOnly Property UserInexistent() As String
            Get
                Return ResourceManager.GetString("UserInexistent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a {0} has just edited..
        '''</summary>
        Friend Shared ReadOnly Property UserJustEdited() As String
            Get
                Return ResourceManager.GetString("UserJustEdited", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User name: .
        '''</summary>
        Friend Shared ReadOnly Property UserName() As String
            Get
                Return ResourceManager.GetString("UserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The user {0} have not edited on this Wiki..
        '''</summary>
        Friend Shared ReadOnly Property UserNoEdits() As String
            Get
                Return ResourceManager.GetString("UserNoEdits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Thread error on page &apos;{0}&apos;. Thread number: {1}. EX: {2}.
        '''</summary>
        Friend Shared ReadOnly Property WikiThreadError() As String
            Get
                Return ResourceManager.GetString("WikiThreadError", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
