'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PeriodiBOT_IRC.SStrings", GetType(SStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=edit{0}&amp;title={1}&amp;summary={2}&amp;section=new&amp;sectiontitle={3}&amp;text={4}&amp;token={5}.
        '''</summary>
        Friend Shared ReadOnly Property AddThread() As String
            Get
                Return ResourceManager.GetString("AddThread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a action=query&amp;assert=bot&amp;format=json.
        '''</summary>
        Friend Shared ReadOnly Property AssertBotData() As String
            Get
                Return ResourceManager.GetString("AssertBotData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a assertbotfailed.
        '''</summary>
        Friend Shared ReadOnly Property AssertBotFailed() As String
            Get
                Return ResourceManager.GetString("AssertBotFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a action=query&amp;assert=user&amp;format=json.
        '''</summary>
        Friend Shared ReadOnly Property AssertUserData() As String
            Get
                Return ResourceManager.GetString("AssertUserData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a assertuserfailed.
        '''</summary>
        Friend Shared ReadOnly Property AssertUserFailed() As String
            Get
                Return ResourceManager.GetString("AssertUserFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;!-- Caja generada por PeriodiBOT, puedes editarla cuanto quieras, pero los nuevos enlaces siempre se añadirán al final. --&gt;.
        '''</summary>
        Friend Shared ReadOnly Property BoxMessage() As String
            Get
                Return ResourceManager.GetString("BoxMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ======================CONFIG======================
        '''BOTName=&quot;{0}&quot;
        '''WPUserName=&quot;{1}&quot;
        '''WPBotPassword=&quot;{2}&quot;
        '''PageURL=&quot;{3}&quot;
        '''ApiURL=&quot;{4}&quot;
        '''IRCNetwork=&quot;{5}&quot;
        '''IRCBotNickName=&quot;{6}&quot;
        '''IRCBotPassword=&quot;{7}&quot;
        '''IRCChannel=&quot;{8}&quot;.
        '''</summary>
        Friend Shared ReadOnly Property ConfigTemplate() As String
            Get
                Return ResourceManager.GetString("ConfigTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=query&amp;meta=tokens.
        '''</summary>
        Friend Shared ReadOnly Property EditToken() As String
            Get
                Return ResourceManager.GetString("EditToken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=compare&amp;fromrev={0}&amp;torev={1}.
        '''</summary>
        Friend Shared ReadOnly Property GetDiffQuery() As String
            Get
                Return ResourceManager.GetString("GetDiffQuery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=query&amp;prop=revisions&amp;titles=.
        '''</summary>
        Friend Shared ReadOnly Property GetLastRevIds() As String
            Get
                Return ResourceManager.GetString("GetLastRevIds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;maxlag=5&amp;action=query&amp;prop=revisions&amp;rvprop=timestamp&amp;titles={0}.
        '''</summary>
        Friend Shared ReadOnly Property GetLastTimestamp() As String
            Get
                Return ResourceManager.GetString("GetLastTimestamp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a https://ores.wikimedia.org/v3/scores/eswiki/?models=damaging|goodfaith&amp;format=json&amp;revids=.
        '''</summary>
        Friend Shared ReadOnly Property GetOresScore() As String
            Get
                Return ResourceManager.GetString("GetOresScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=query&amp;list=embeddedin&amp;eilimit=1000&amp;eititle=.
        '''</summary>
        Friend Shared ReadOnly Property GetPageInclusions() As String
            Get
                Return ResourceManager.GetString("GetPageInclusions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=query&amp;prop=extracts&amp;exintro=&amp;explaintext=&amp;titles=.
        '''</summary>
        Friend Shared ReadOnly Property GetPagesExtract() As String
            Get
                Return ResourceManager.GetString("GetPagesExtract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=query&amp;formatversion=2&amp;prop=pageimages&amp;titles=.
        '''</summary>
        Friend Shared ReadOnly Property GetPagesImage() As String
            Get
                Return ResourceManager.GetString("GetPagesImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/{0}/all-access/all-agents/{1}/daily/{2}{4}{6}00/{3}{5}{7}00.
        '''</summary>
        Friend Shared ReadOnly Property GetPageViews() As String
            Get
                Return ResourceManager.GetString("GetPageViews", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=query&amp;meta=tokens&amp;type=login.
        '''</summary>
        Friend Shared ReadOnly Property GetWikiToken() As String
            Get
                Return ResourceManager.GetString("GetWikiToken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¡Hola! Este mensaje es un aviso automático a todos los miembros activos de [[Wikipedia:Mediación informal/Participantes/Lista|Mediación informal]] para informar de una [[Wikipedia:Mediación informal/Solicitudes|nueva solicitud]]. Por favor, considera participar en la discusión.
        '''
        '''¡Gracias por tu atención! ~~~~.
        '''</summary>
        Friend Shared ReadOnly Property InfMedMsg() As String
            Get
                Return ResourceManager.GetString("InfMedMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a InformalMediationLastThreadCount.
        '''</summary>
        Friend Shared ReadOnly Property InfMedSettingsName() As String
            Get
                Return ResourceManager.GetString("InfMedSettingsName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (Bot) Aviso automático de una nueva solicitud en [[Wikipedia:Mediación informal/Participantes/Lista|Mediación informal]]..
        '''</summary>
        Friend Shared ReadOnly Property InfMedSumm() As String
            Get
                Return ResourceManager.GetString("InfMedSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Atención en [[Wikipedia:Mediación informal/Solicitudes|Mediación informal]].
        '''</summary>
        Friend Shared ReadOnly Property InfMedTitle() As String
            Get
                Return ResourceManager.GetString("InfMedTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IRC.
        '''</summary>
        Friend Shared ReadOnly Property IrcSource() As String
            Get
                Return ResourceManager.GetString("IrcSource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LOCAL.
        '''</summary>
        Friend Shared ReadOnly Property LocalSource() As String
            Get
                Return ResourceManager.GetString("LocalSource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=login&amp;lgname={0}&amp;lgpassword={1}&amp;lgdomain=&amp;lgtoken={2}.
        '''</summary>
        Friend Shared ReadOnly Property Login() As String
            Get
                Return ResourceManager.GetString("Login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario:PeriodiBOT/Curiosidades/Hilos más largos en la historia del café.
        '''</summary>
        Friend Shared ReadOnly Property LongestThreads() As String
            Get
                Return ResourceManager.GetString("LongestThreads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a https://ores.wikimedia.org/v3/scores/eswiki/?models=damaging|goodfaith&amp;format=json&amp;revids=.
        '''</summary>
        Friend Shared ReadOnly Property OresScoresApiQueryUrl() As String
            Get
                Return ResourceManager.GetString("OresScoresApiQueryUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;maxlag=5&amp;action=query&amp;prop=revisions|pageimages|categories|extracts&amp;rvprop=user|timestamp|size|content|ids&amp;exlimit=1&amp;explaintext&amp;exintro&amp;titles={0}.
        '''</summary>
        Friend Shared ReadOnly Property PageInfo() As String
            Get
                Return ResourceManager.GetString("PageInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;maxlag=5&amp;action=query&amp;prop=revisions|pageimages|categories|extracts&amp;rvprop=user|timestamp|size|content|ids&amp;exlimit=1&amp;explaintext&amp;exintro&amp;revids={0}.
        '''</summary>
        Friend Shared ReadOnly Property PageInfoRevid() As String
            Get
                Return ResourceManager.GetString("PageInfoRevid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=query&amp;pslimit=max&amp;list=prefixsearch&amp;pssearch=.
        '''</summary>
        Friend Shared ReadOnly Property PrefixSearchQuery() As String
            Get
                Return ResourceManager.GetString("PrefixSearchQuery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=edit{0}&amp;title={1}&amp;summary={2}&amp;text={4}&amp;token={3}.
        '''</summary>
        Friend Shared ReadOnly Property SavePage() As String
            Get
                Return ResourceManager.GetString("SavePage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=query&amp;list=search&amp;utf8=1&amp;srsearch=.
        '''</summary>
        Friend Shared ReadOnly Property Search() As String
            Get
                Return ResourceManager.GetString("Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a format=json&amp;action=query&amp;list=search&amp;utf8=1&amp;srnamespace=2&amp;srsearch=.
        '''</summary>
        Friend Shared ReadOnly Property SearchForUser() As String
            Get
                Return ResourceManager.GetString("SearchForUser", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
