'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class StaticVars
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PeriodiBOT_IRC.StaticVars", GetType(StaticVars).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a action=query&amp;assert=bot&amp;format=json.
        '''</summary>
        Friend Shared ReadOnly Property AssertBotData() As String
            Get
                Return ResourceManager.GetString("AssertBotData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a assertbotfailed.
        '''</summary>
        Friend Shared ReadOnly Property AssertBotFailed() As String
            Get
                Return ResourceManager.GetString("AssertBotFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a action=query&amp;assert=user&amp;format=json.
        '''</summary>
        Friend Shared ReadOnly Property AssertUserData() As String
            Get
                Return ResourceManager.GetString("AssertUserData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a assertuserfailed.
        '''</summary>
        Friend Shared ReadOnly Property AssertUserFailed() As String
            Get
                Return ResourceManager.GetString("AssertUserFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ======================CONFIG======================
        '''BOTName=&quot;{0}&quot;
        '''WPUserName=&quot;{1}&quot;
        '''WPBotPassword=&quot;{2}&quot;
        '''PageURL=&quot;{3}&quot;
        '''ApiURL=&quot;{4}&quot;
        '''IRCNetwork=&quot;{5}&quot;
        '''IRCBotNickName=&quot;{6}&quot;
        '''IRCBotPassword=&quot;{7}&quot;
        '''IRCChannel=&quot;{8}&quot;.
        '''</summary>
        Friend Shared ReadOnly Property ConfigTemplate() As String
            Get
                Return ResourceManager.GetString("ConfigTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LOCAL.
        '''</summary>
        Friend Shared ReadOnly Property LocalSource() As String
            Get
                Return ResourceManager.GetString("LocalSource", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
