'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class BotMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PeriodiBOT_IRC.BotMessages", GetType(BotMessages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Se añadió {0} extracto nuevo..
        '''</summary>
        Public Shared ReadOnly Property AddedExtract() As String
            Get
                Return ResourceManager.GetString("AddedExtract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Se añadieron {0} extractos nuevos..
        '''</summary>
        Public Shared ReadOnly Property AddedExtracts() As String
            Get
                Return ResourceManager.GetString("AddedExtracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivado de páginas completo..
        '''</summary>
        Public Shared ReadOnly Property AllArchived() As String
            Get
                Return ResourceManager.GetString("AllArchived", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aparentemente el resultado es {0}..
        '''</summary>
        Public Shared ReadOnly Property ApparentResult() As String
            Get
                Return ResourceManager.GetString("ApparentResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bot: Archivando {0} hilo con más de {1} días de antigüedad desde &apos;{2}&apos;..
        '''</summary>
        Public Shared ReadOnly Property ArchivedThreadDestSumm() As String
            Get
                Return ResourceManager.GetString("ArchivedThreadDestSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bot: Archivando {0} hilos con más de {1} días de antigüedad desde &apos;{2}&apos;..
        '''</summary>
        Public Shared ReadOnly Property ArchivedThreadsDestSumm() As String
            Get
                Return ResourceManager.GetString("ArchivedThreadsDestSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bot: Archivando {0} hilos con más de {1} días de antigüedad..
        '''</summary>
        Public Shared ReadOnly Property ArchivedThreadsSumm() As String
            Get
                Return ResourceManager.GetString("ArchivedThreadsSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bot: Archivando {0} hilo con más de {1} días de antigüedad..
        '''</summary>
        Public Shared ReadOnly Property ArchivedThreadSumm() As String
            Get
                Return ResourceManager.GetString("ArchivedThreadSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivando todas las páginas que incluyan la plantilla &apos;{0}&apos;..
        '''</summary>
        Public Shared ReadOnly Property ArchivingInclusions() As String
            Get
                Return ResourceManager.GetString("ArchivingInclusions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Autor : .
        '''</summary>
        Public Shared ReadOnly Property Author() As String
            Get
                Return ResourceManager.GetString("Author", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Autoarchivando &apos;{0}&apos;..
        '''</summary>
        Public Shared ReadOnly Property AutoArchive() As String
            Get
                Return ResourceManager.GetString("AutoArchive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Autoarchivado de &apos;{0}&apos; completo..
        '''</summary>
        Public Shared ReadOnly Property AutoArchiveDone() As String
            Get
                Return ResourceManager.GetString("AutoArchiveDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelada :.
        '''</summary>
        Public Shared ReadOnly Property Cancelled() As String
            Get
                Return ResourceManager.GetString("Cancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La tarea crítica &apos;{0}&apos; no puede ser pausada..
        '''</summary>
        Public Shared ReadOnly Property CannotPause() As String
            Get
                Return ResourceManager.GetString("CannotPause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comprobando el usuario {0}.
        '''</summary>
        Public Shared ReadOnly Property CheckingUser() As String
            Get
                Return ResourceManager.GetString("CheckingUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verificando si el usuario {0} en el host {1} es OP..
        '''</summary>
        Public Shared ReadOnly Property CheckOp() As String
            Get
                Return ResourceManager.GetString("CheckOp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comando &apos;{0}&apos; ingresado por &apos;{1}&apos;. Argumentos: &apos;{2}&apos;.
        '''</summary>
        Public Shared ReadOnly Property CommandIssued() As String
            Get
                Return ResourceManager.GetString("CommandIssued", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error de conexión. EX: {0}.
        '''</summary>
        Public Shared ReadOnly Property ConnectionError() As String
            Get
                Return ResourceManager.GetString("ConnectionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Bot) Creando nueva caja de archivos..
        '''</summary>
        Public Shared ReadOnly Property CreatingBoxSumm() As String
            Get
                Return ResourceManager.GetString("CreatingBoxSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creando conexión..
        '''</summary>
        Public Shared ReadOnly Property CreatingConnection() As String
            Get
                Return ResourceManager.GetString("CreatingConnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crítica : .
        '''</summary>
        Public Shared ReadOnly Property Critical() As String
            Get
                Return ResourceManager.GetString("Critical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log debug desactivado..
        '''</summary>
        Public Shared ReadOnly Property DebugDisabled() As String
            Get
                Return ResourceManager.GetString("DebugDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log debug activado..
        '''</summary>
        Public Shared ReadOnly Property DebugEnabled() As String
            Get
                Return ResourceManager.GetString("DebugEnabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dividiendo por 0....
        '''</summary>
        Public Shared ReadOnly Property Div0() As String
            Get
                Return ResourceManager.GetString("Div0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resultado de la edición en &apos;{0}&apos;: {1}.
        '''</summary>
        Public Shared ReadOnly Property EditResultMessage() As String
            Get
                Return ResourceManager.GetString("EditResultMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entrando a {0}..
        '''</summary>
        Public Shared ReadOnly Property EnteringRoom() As String
            Get
                Return ResourceManager.GetString("EnteringRoom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingrese el número de la tarea..
        '''</summary>
        Public Shared ReadOnly Property EnterTaskNumber() As String
            Get
                Return ResourceManager.GetString("EnterTaskNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Errores : .
        '''</summary>
        Public Shared ReadOnly Property Errors() As String
            Get
                Return ResourceManager.GetString("Errors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cada {0} segundos..
        '''</summary>
        Public Shared ReadOnly Property EverySec() As String
            Get
                Return ResourceManager.GetString("EverySec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eejcuciones : .
        '''</summary>
        Public Shared ReadOnly Property Executions() As String
            Get
                Return ResourceManager.GetString("Executions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK, me voy....
        '''</summary>
        Public Shared ReadOnly Property ExitMessage() As String
            Get
                Return ResourceManager.GetString("ExitMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error al crear el archivo &apos;{0}&apos;..
        '''</summary>
        Public Shared ReadOnly Property FileCreateErr() As String
            Get
                Return ResourceManager.GetString("FileCreateErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error al guardar el archivo &apos;{0}&apos;..
        '''</summary>
        Public Shared ReadOnly Property FileSaveErr() As String
            Get
                Return ResourceManager.GetString("FileSaveErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargando el extracto de la página &apos;{0}&apos;..
        '''</summary>
        Public Shared ReadOnly Property GetPageExtract() As String
            Get
                Return ResourceManager.GetString("GetPageExtract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargando {0} extractos de páginas..
        '''</summary>
        Public Shared ReadOnly Property GetPagesExtract() As String
            Get
                Return ResourceManager.GetString("GetPagesExtract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Infinita : .
        '''</summary>
        Public Shared ReadOnly Property Infinite() As String
            Get
                Return ResourceManager.GetString("Infinite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El espacio de nombres de la página &apos;{0}&apos; ({1}) es inválido..
        '''</summary>
        Public Shared ReadOnly Property InvalidNamespace() As String
            Get
                Return ResourceManager.GetString("InvalidNamespace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El nombre de la página es inválido.
        '''</summary>
        Public Shared ReadOnly Property InvalidPageName() As String
            Get
                Return ResourceManager.GetString("InvalidPageName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parámetro inválido..
        '''</summary>
        Public Shared ReadOnly Property InvalidParameter() As String
            Get
                Return ResourceManager.GetString("InvalidParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid parameter..
        '''</summary>
        Public Shared ReadOnly Property InvalidParameter1() As String
            Get
                Return ResourceManager.GetString("InvalidParameter1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario &apos;{0}&apos; no cumple con los requisitos mínimos..
        '''</summary>
        Public Shared ReadOnly Property InvalidUser() As String
            Get
                Return ResourceManager.GetString("InvalidUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario &apos;{0}&apos; no cumple con los requisitos mínimos de archivado..
        '''</summary>
        Public Shared ReadOnly Property InvalidUserArchive() As String
            Get
                Return ResourceManager.GetString("InvalidUserArchive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entrando al canal {0}..
        '''</summary>
        Public Shared ReadOnly Property JoiningChannel() As String
            Get
                Return ResourceManager.GetString("JoiningChannel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saliendo de {0}..
        '''</summary>
        Public Shared ReadOnly Property LeavingRoom() As String
            Get
                Return ResourceManager.GetString("LeavingRoom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargando {0} resúmenes nuevos..
        '''</summary>
        Public Shared ReadOnly Property LoadingNewExtracts() As String
            Get
                Return ResourceManager.GetString("LoadingNewExtracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargando {0} resúmenes antiguos..
        '''</summary>
        Public Shared ReadOnly Property LoadingOldExtracts() As String
            Get
                Return ResourceManager.GetString("LoadingOldExtracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargando operadores..
        '''</summary>
        Public Shared ReadOnly Property LoadingOPs() As String
            Get
                Return ResourceManager.GetString("LoadingOPs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conexión perdida. Reintentando en {0} segundos..
        '''</summary>
        Public Shared ReadOnly Property LostConnectionRET() As String
            Get
                Return ResourceManager.GetString("LostConnectionRET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La plantilla de archivado en la página &apos;{0}&apos; está malformada..
        '''</summary>
        Public Shared ReadOnly Property MalformedArchiveConfig() As String
            Get
                Return ResourceManager.GetString("MalformedArchiveConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivo de operadores malformado..
        '''</summary>
        Public Shared ReadOnly Property MalformedOPs() As String
            Get
                Return ResourceManager.GetString("MalformedOPs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El valor debe ser superior a {0}..
        '''</summary>
        Public Shared ReadOnly Property MustBeGreaterThan() As String
            Get
                Return ResourceManager.GetString("MustBeGreaterThan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre : .
        '''</summary>
        Public Shared ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dirección del servidor de IRC principal: .
        '''</summary>
        Public Shared ReadOnly Property NewIrcNetworkAdress() As String
            Get
                Return ResourceManager.GetString("NewIrcNetworkAdress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Canales de IRC (separados por pipe [|]): .
        '''</summary>
        Public Shared ReadOnly Property NewIrcNetworkChannels() As String
            Get
                Return ResourceManager.GetString("NewIrcNetworkChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nickname en el servidor IRC: .
        '''</summary>
        Public Shared ReadOnly Property NewIrcNetworkNickName() As String
            Get
                Return ResourceManager.GetString("NewIrcNetworkNickName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contraseña de Nickserv o de servidor: .
        '''</summary>
        Public Shared ReadOnly Property NewIrcNetworkPass() As String
            Get
                Return ResourceManager.GetString("NewIrcNetworkPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operador IRC (Nickname!hostname):.
        '''</summary>
        Public Shared ReadOnly Property NewOp() As String
            Get
                Return ResourceManager.GetString("NewOp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to . El próximo aviso será en 5 minutos..
        '''</summary>
        Public Shared ReadOnly Property NextNotif() As String
            Get
                Return ResourceManager.GetString("NextNotif", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Intentando autenticar via nickserv..
        '''</summary>
        Public Shared ReadOnly Property NickervAuth() As String
            Get
                Return ResourceManager.GetString("NickervAuth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No existe el archivo de configuracion IRC.
        '''</summary>
        Public Shared ReadOnly Property NoIrcConfigFile() As String
            Get
                Return ResourceManager.GetString("NoIrcConfigFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se ha definido ningun operador..
        '''</summary>
        Public Shared ReadOnly Property NoOp() As String
            Get
                Return ResourceManager.GetString("NoOp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El archivo de operadores no existe..
        '''</summary>
        Public Shared ReadOnly Property NoOpsFile() As String
            Get
                Return ResourceManager.GetString("NoOpsFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No hay tareas en ejecución..
        '''</summary>
        Public Shared ReadOnly Property NoRunningTasks() As String
            Get
                Return ResourceManager.GetString("NoRunningTasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La página &apos;{0}&apos; no es una subpágina de la página principal (&apos;{1}&apos;)..
        '''</summary>
        Public Shared ReadOnly Property NotASubPage() As String
            Get
                Return ResourceManager.GetString("NotASubPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No conectado..
        '''</summary>
        Public Shared ReadOnly Property NotConnected() As String
            Get
                Return ResourceManager.GetString("NotConnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No hay hilos por archivar en &apos;{0}&apos;..
        '''</summary>
        Public Shared ReadOnly Property NothingToArchive() As String
            Get
                Return ResourceManager.GetString("NothingToArchive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se ha completado la firma en &apos;{0}&apos;..
        '''</summary>
        Public Shared ReadOnly Property NotSigned() As String
            Get
                Return ResourceManager.GetString("NotSigned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El parámetro es nulo..
        '''</summary>
        Public Shared ReadOnly Property NullParameter() As String
            Get
                Return ResourceManager.GetString("NullParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingrese un valor numérico.
        '''</summary>
        Public Shared ReadOnly Property NumericValue() As String
            Get
                Return ResourceManager.GetString("NumericValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Se omitió {0} extracto inseguro..
        '''</summary>
        Public Shared ReadOnly Property OmittedExtract() As String
            Get
                Return ResourceManager.GetString("OmittedExtract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Se omitieron {0} extractos inseguros..
        '''</summary>
        Public Shared ReadOnly Property OmittedExtracts() As String
            Get
                Return ResourceManager.GetString("OmittedExtracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La página &apos;{0}&apos; solo tiene un hilo..
        '''</summary>
        Public Shared ReadOnly Property OneThreadPage() As String
            Get
                Return ResourceManager.GetString("OneThreadPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario {0} ha sido añadido como operador..
        '''</summary>
        Public Shared ReadOnly Property OpAdded() As String
            Get
                Return ResourceManager.GetString("OpAdded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario {0} no ha sido añadido como operador..
        '''</summary>
        Public Shared ReadOnly Property OpNotAdded() As String
            Get
                Return ResourceManager.GetString("OpNotAdded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} no es un operador..
        '''</summary>
        Public Shared ReadOnly Property OpNotRemoved() As String
            Get
                Return ResourceManager.GetString("OpNotRemoved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} ya no es un operador..
        '''</summary>
        Public Shared ReadOnly Property OpRemoved() As String
            Get
                Return ResourceManager.GetString("OpRemoved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Bot) Creando una nueva caja de archivos por sobre una ya existente..
        '''</summary>
        Public Shared ReadOnly Property OverwritingBoxSumm() As String
            Get
                Return ResourceManager.GetString("OverwritingBoxSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pausada : .
        '''</summary>
        Public Shared ReadOnly Property Paused() As String
            Get
                Return ResourceManager.GetString("Paused", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tarea &apos;{0}&apos; pausada..
        '''</summary>
        Public Shared ReadOnly Property PausedTask() As String
            Get
                Return ResourceManager.GetString("PausedTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Periódica.
        '''</summary>
        Public Shared ReadOnly Property Periodic() As String
            Get
                Return ResourceManager.GetString("Periodic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recreando texto..
        '''</summary>
        Public Shared ReadOnly Property RecreatingText() As String
            Get
                Return ResourceManager.GetString("RecreatingText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Solicitado por un operador..
        '''</summary>
        Public Shared ReadOnly Property RequestedByOp() As String
            Get
                Return ResourceManager.GetString("RequestedByOp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hay {0} tareas ejecutándose en este momento..
        '''</summary>
        Public Shared ReadOnly Property RunningTasks() As String
            Get
                Return ResourceManager.GetString("RunningTasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estableciendo nombre..
        '''</summary>
        Public Shared ReadOnly Property SetName() As String
            Get
                Return ResourceManager.GetString("SetName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estableciendo nickname..
        '''</summary>
        Public Shared ReadOnly Property SetNick() As String
            Get
                Return ResourceManager.GetString("SetNick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programada.
        '''</summary>
        Public Shared ReadOnly Property Sheduled() As String
            Get
                Return ResourceManager.GetString("Sheduled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting IRC client..
        '''</summary>
        Public Shared ReadOnly Property StartingIRCClient() As String
            Get
                Return ResourceManager.GetString("StartingIRCClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estado : .
        '''</summary>
        Public Shared ReadOnly Property Status() As String
            Get
                Return ResourceManager.GetString("Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operación exitosa..
        '''</summary>
        Public Shared ReadOnly Property SuccessfulOperation() As String
            Get
                Return ResourceManager.GetString("SuccessfulOperation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La hora del sistema es: .
        '''</summary>
        Public Shared ReadOnly Property SystemTime() As String
            Get
                Return ResourceManager.GetString("SystemTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: {1} por {2}. Estado: {3}..
        '''</summary>
        Public Shared ReadOnly Property TaskInfo() As String
            Get
                Return ResourceManager.GetString("TaskInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La tarea no existe..
        '''</summary>
        Public Shared ReadOnly Property TaskNotExist() As String
            Get
                Return ResourceManager.GetString("TaskNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tiempo/Intervalo : .
        '''</summary>
        Public Shared ReadOnly Property TimeOrInterval() As String
            Get
                Return ResourceManager.GetString("TimeOrInterval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Intentando guardar &apos;{0}&apos;..
        '''</summary>
        Public Shared ReadOnly Property TryingToSave() As String
            Get
                Return ResourceManager.GetString("TryingToSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo : .
        '''</summary>
        Public Shared ReadOnly Property Type() As String
            Get
                Return ResourceManager.GetString("Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No autorizado..
        '''</summary>
        Public Shared ReadOnly Property Unauthorized() As String
            Get
                Return ResourceManager.GetString("Unauthorized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excepción inesperada: {0}.
        '''</summary>
        Public Shared ReadOnly Property UnexpectedEX() As String
            Get
                Return ResourceManager.GetString("UnexpectedEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tarea &apos;{0}&apos; despausada..
        '''</summary>
        Public Shared ReadOnly Property UnpausedTask() As String
            Get
                Return ResourceManager.GetString("UnpausedTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mensaje sin firmar detectado en &apos;{0}&apos;..
        '''</summary>
        Public Shared ReadOnly Property UnsignedMessageDetected() As String
            Get
                Return ResourceManager.GetString("UnsignedMessageDetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bot: Añadiendo firma faltante de [[Usuario:{0}|{0}]]..
        '''</summary>
        Public Shared ReadOnly Property UnsignedSumm() As String
            Get
                Return ResourceManager.GetString("UnsignedSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La operación ha fallado..
        '''</summary>
        Public Shared ReadOnly Property UnsuccessfulOperation() As String
            Get
                Return ResourceManager.GetString("UnsuccessfulOperation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error al actualizar la caja de archivos en &apos;{0}&apos;. EX: {1}.
        '''</summary>
        Public Shared ReadOnly Property UpdateBoxEx() As String
            Get
                Return ResourceManager.GetString("UpdateBoxEx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bot: {0} resúmenes actualizados..
        '''</summary>
        Public Shared ReadOnly Property UpdatedExtracts() As String
            Get
                Return ResourceManager.GetString("UpdatedExtracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actualizando caja de archivos..
        '''</summary>
        Public Shared ReadOnly Property UpdatingArchiveBox() As String
            Get
                Return ResourceManager.GetString("UpdatingArchiveBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bot: Actualizando caja de archivos..
        '''</summary>
        Public Shared ReadOnly Property UpdatingBoxSumm() As String
            Get
                Return ResourceManager.GetString("UpdatingBoxSumm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bot: Actualizando contador..
        '''</summary>
        Public Shared ReadOnly Property UpdatingCount() As String
            Get
                Return ResourceManager.GetString("UpdatingCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario {0} está bloqueado..
        '''</summary>
        Public Shared ReadOnly Property UserBlocked() As String
            Get
                Return ResourceManager.GetString("UserBlocked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La última edición de {0} fue hace {1} día..
        '''</summary>
        Public Shared ReadOnly Property UserEditedDay() As String
            Get
                Return ResourceManager.GetString("UserEditedDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La última edición de {0} fue hace {1} días..
        '''</summary>
        Public Shared ReadOnly Property UserEditedDays() As String
            Get
                Return ResourceManager.GetString("UserEditedDays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La última edición de {0} fue hace {1} hora..
        '''</summary>
        Public Shared ReadOnly Property UserEditedHour() As String
            Get
                Return ResourceManager.GetString("UserEditedHour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La última edición de {0} fue hace {1} horas..
        '''</summary>
        Public Shared ReadOnly Property UserEditedHours() As String
            Get
                Return ResourceManager.GetString("UserEditedHours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La última edición de {0} fue hace {1} minutos..
        '''</summary>
        Public Shared ReadOnly Property UserEditedMinutes() As String
            Get
                Return ResourceManager.GetString("UserEditedMinutes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario {0} está inactivo..
        '''</summary>
        Public Shared ReadOnly Property UserInactive() As String
            Get
                Return ResourceManager.GetString("UserInactive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario {0} no existe..
        '''</summary>
        Public Shared ReadOnly Property UserInexistent() As String
            Get
                Return ResourceManager.GetString("UserInexistent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario {0} no tiene ediciones en esta Wiki..
        '''</summary>
        Public Shared ReadOnly Property UserNoEdits() As String
            Get
                Return ResourceManager.GetString("UserNoEdits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario {0} en el host {1} no es OP..
        '''</summary>
        Public Shared ReadOnly Property UserNotOp() As String
            Get
                Return ResourceManager.GetString("UserNotOp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario {0} en el host {1} es OP..
        '''</summary>
        Public Shared ReadOnly Property UserOP() As String
            Get
                Return ResourceManager.GetString("UserOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El valor es demasiado grande..
        '''</summary>
        Public Shared ReadOnly Property ValueTooBig() As String
            Get
                Return ResourceManager.GetString("ValueTooBig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tiempo de espera: {0}ms..
        '''</summary>
        Public Shared ReadOnly Property WaitingTime() As String
            Get
                Return ResourceManager.GetString("WaitingTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error en un hilo de la página &apos;{0}&apos;. Hilo número {1}. EX: {2}.
        '''</summary>
        Public Shared ReadOnly Property WikiThreadError() As String
            Get
                Return ResourceManager.GetString("WikiThreadError", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
